### ISSUE TITLE
How do we run this on deno ?

### ISSUE THREAD

**Issue by anjanesh** [GantMan/learn-tfjs#12]
This not TFJS specific - I'm trying to get this running via deno - not nodejs, so no node_modules.

```ts
import tfjs from "https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.0.0/dist/tf.min.js";
import * as toxicity from "https://cdn.jsdelivr.net/npm/@tensorflow-models/toxicity@1.2.2";
const threshold = 0.5;
toxicity.load(threshold).then((model: any) =>
{
    //
});
```
I get :
```
error: TS2339 [ERROR]: Property 'load' does not exist on type 'typeof import("https://cdn.jsdelivr.net/npm/@tensorflow-models/toxicity@1.2.2")'.
```

**Comment by anjanesh** [comment]
Apparently from deno 1.25 onwards we can do this :

```ts
import tfjs from "npm:tensorflow";
import * as toxicity from "npm:tensorflow-models/toxicity";
```

But I get this :

```
error: Unable to load /Users/username/Library/Caches/deno/npm/registry.npmjs.org/tensorflow-models/0.0.1/toxicity imported from file:///Users/username/test/toxicity.ts

Caused by:
    Is a directory (os error 21)
```

**Comment by joshuayoes** [comment]
Hey @anjanesh 👋 

I think this page from the deno docs will be really helpful here: https://deno.land/manual@v1.29.2/node/npm_specifiers#using-npm-packages-with-npm-specifiers

First suggestion: make sure to add your version numbers at the end of your library name, or else you may implicitly get different versions. Try this:

```ts
import tfjs from "npm:tensorflow@3.0.0";
import * as toxicity from "npm:@tensorflow-models/toxicity@1.2.2";
```

I notice in your error message, it is pulling 0.0.1 for tensorflow-models/toxicity instead of 1.2.2.

--- 

Another helpful tip may be to use the `--node-modules-dir` [flag in deno to generate a node_modules directory](https://deno.land/manual@v1.29.2/node/npm_specifiers#--node-modules-dir-flag). This can be helpful to debug these kind of issues.

**Comment by joshuayoes** [comment]
Additionally, import maps may be helpful here to let you specify where to source package names from within a project in one place: https://deno.land/manual@v1.29.2/node/import_maps

**Comment by anjanesh** [comment]
Hey man - you solved my problem(s) ! Thanks.

Some additional changes required :

```
import tfjs from "npm:@tensorflow/tfjs@4.2.0";
import * as toxicity from "npm:@tensorflow-models/toxicity@1.2.2";
```

`error: npm package '@types/node-fetch' does not exist`

Need this in tsconfig.json because apparently 'ESM support in ts-node is currently experimental.' (https://stackoverflow.com/a/70074080/126833)

```
{
  "compilerOptions": {
    "module": "esnext"
  }
}
```
